include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore