// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'misc/failure_test.dart' as misc_failure_test;
import 'misc/margins_test.dart' as misc_margins_test;
import 'service_tests/api_test.dart' as service_tests_api_test;
import 'service_tests/local_db_test.dart' as service_tests_local_db_test;
import 'viewmodel_tests/feed_viewmodel_test.dart' as viewmodel_tests_feed_viewmodel_test;
import 'viewmodel_tests/home_viewmodel_test.dart' as viewmodel_tests_home_viewmodel_test;
import 'viewmodel_tests/startup_viewmodel_test.dart' as viewmodel_tests_startup_viewmodel_test;
import 'widget_tests/feed_view_test.dart' as widget_tests_feed_view_test;
import 'widget_tests/home_view_test.dart' as widget_tests_home_view_test;
import 'widget_tests/startup_view_test.dart' as widget_tests_startup_view_test;
import 'widget_tests/widgets/appbar_test.dart' as widget_tests_widgets_appbar_test;

void main() {
  misc_failure_test.main();
  misc_margins_test.main();
  service_tests_local_db_test.main();
  service_tests_api_test.main();
  viewmodel_tests_home_viewmodel_test.main();
  viewmodel_tests_feed_viewmodel_test.main();
  viewmodel_tests_startup_viewmodel_test.main();
  widget_tests_home_view_test.main();
  widget_tests_startup_view_test.main();
  widget_tests_widgets_appbar_test.main();
  widget_tests_feed_view_test.main();
}
