name: issue open
on:
  issues:
      types: ['opened']
jobs:
  opened-issue-label:
    name: adding Issue Label
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["unapproved"]'
  
  Issue-Greeting:
    name: Greeting Message to User
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congratulations on making your first Issue! :confetti_ball: If you haven't already, check out our [Code of Conduct](https://github.com/dscnitrourkela/project-elaichi/blob/main/CONTRIBUTING.md) and [Contributing Guidelines](https://github.com/dscnitrourkela/project-elaichi/blob/main/CODE_OF_CONDUCT.md) to ensure that you are following our guidelines for contributing and making issues."
